services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: phpdocker-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=myapp
      - DB_USER=postgres
      - DB_PASSWORD=secret
    depends_on:
      - db

  nginx:
    image: nginx:1.19-alpine
    container_name: phpdocker-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: phpdocker-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: